apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.0
          ports:
            - containerPort: 80
              name: "nginx-port"
          volumeMounts:
          - name: nginx-config
            mountPath: "/etc/nginx/"
            readOnly: true
          - name: logdir
            mountPath: "/var/logs/nginx/"

        - name: fluentd
          image: fluentd:latest
          volumeMounts:
          - name: fluentd-config
            mountPath: "/fluentd/etc"
          - name: logdir
            mountPath: "/logs"
          
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-conf
          defaultMode: 0400

      - name: fluentd-config
        configMap:
          name: fluentd-conf
          defaultMode: 0644
      - name: logdir
        emptyDir: {}
